name: E-Motion
type: environment
description: Environment for e-motion D4G
dependencies:
- python=3.9
- geopandas=0.12.2
- folium=0.14.0
- scikit-learn=1.2.2
- conda-forge::umap-learn=0.5.3
- numpy=1.20
- pyarrow=10.0.1
- seaborn=0.12.2
- conda-forge::ipywidgets=8.0.4
- conda-forge::dask-geopandas=0.3.0
- anaconda::ipython_genutils=0.2.0
- conda-forge::css-html-js-minify
- conda-forge::mapbox=0.18.1
